import type { Standl } from "@/types/standl";

export const mockStandl: Standl[] = [
    {
        id: "standl-001",
        name: "Hendl Maxl",
        category: "hendl",
        locationName: "Hauptplatz Linz",
        postalCode: "4020",
        city: "Linz",
        latitude: 48.3069,
        longitude: 14.2858,
        openingStatus: {
            type: "open",
            label: "Heute geöffnet",
            source: "owner",
        },
        likes: 24,
        isClaimed: true,
        distanceKm: 2.4,
    },
    {
        id: "standl-002",
        name: "Fischstandl Donau",
        category: "steckerlfisch",
        locationName: "Donaulände Ottensheim",
        postalCode: "4100",
        city: "Ottensheim",
        latitude: 48.3311,
        longitude: 14.1742,
        openingStatus: {
            type: "likelyOpen",
            label: "Heute vermutlich da",
            source: "community",
        },
        likes: 18,
        isClaimed: false,
        distanceKm: 7.8,
    },
    {
        id: "standl-003",
        name: "Grillhendl Mühlviertel",
        category: "hendl",
        locationName: "Marktplatz Freistadt",
        postalCode: "4240",
        city: "Freistadt",
        latitude: 48.511,
        longitude: 14.504,
        openingStatus: {
            type: "opensLater",
            label: "Öffnet um 11:00",
            source: "owner",
        },
        likes: 31,
        isClaimed: true,
    },
    {
        id: "standl-004",
        name: "Steckerlfisch Sepp",
        category: "steckerlfisch",
        locationName: "Badesee Feldkirchen",
        postalCode: "4101",
        city: "Feldkirchen an der Donau",
        latitude: 48.345,
        longitude: 14.051,
        openingStatus: {
            type: "temporaryClosed",
            label: "Heute geschlossen – Wetter",
            source: "owner",
        },
        likes: 12,
        isClaimed: true,
    },
    {
        id: "standl-005",
        name: "Hendlstandl beim Spar",
        category: "hendl",
        locationName: "Spar Parkplatz Hagenberg",
        postalCode: "4232",
        city: "Hagenberg im Mühlkreis",
        latitude: 48.367,
        longitude: 14.516,
        openingStatus: {
            type: "unknown",
            label: "Keine Standzeit bekannt",
            source: "unknown",
        },
        likes: 6,
        isClaimed: false,
    },
];